# -*- coding: utf-8 -*-
"""Physical geometry constants for the Stewart platform rig.

Measured values only — runtime configuration lives in settings.py.
All servo/platform arrays are 0-indexed (indices 0-5) and match the wiring
documented in firmware/README.md (command index i drives Arduino pin D2+i).
"""

import numpy as np

# =========================
# PLATFORM / SERVO GEOMETRY
# =========================

# Neutral platform height (center of platform plane)
Z_NEUTRAL = 151.5

# Servo arm length (shaft center -> arm ball joint center)
ARM_LENGTH = 26.5   # <-- change if needed

# Rod length (arm ball joint -> platform ball joint)
ROD_LENGTH = 163.0  # <-- your measured U-joint/balljoint distance

# Platform size (square side length)
PLATFORM_SIZE = 240.0

# =========================
# SERVO SHAFT LOCATIONS (XY)
# =========================
# Generated from one measured mirror pair — servos 0/5 at (93.0, +/-37.5) —
# with servos 1-4 produced by rotating that pair +/-120 deg about Z.
# Consequence: all six shafts sit at r = 100.276 mm from center.
# Validated 2026-06-11 (radius + rotation-symmetry check; servo 4 Y was a
# digit transposition -99.920 -> -99.290, fixed in PR #15).

SERVO_SHAFTS_XY = np.array([
    (93.0, 37.5),
    (-14.024, 99.290),
    (-78.976, 61.790),
    (-78.976, -61.790),
    (-14.024, -99.290),
    (93.0, -37.5),
], dtype=float)

# Full 3D shaft centers (z=0 always)
SERVO_SHAFTS = np.column_stack((SERVO_SHAFTS_XY, np.zeros(6)))


# =========================
# PLATFORM BALL JOINT POINTS
# =========================
# Same construction as the shafts: mirror pair 0/5 measured, pairs 1-4
# generated by +/-120 deg rotation about Z. All six points sit at
# r = 81.978 mm from platform center (verified 2026-06-11, table clean).

PLATFORM_POINTS_LOCAL_XY = np.array([
    (55.502, 60.332),
    (24.498, 78.232),
    (-80, 17.9),
    (-80, -17.9),
    (24.498, -78.232),
    (55.502, -60.332),
], dtype=float)

# Local platform points in its own coordinate frame (z=0 plane)
PLATFORM_POINTS_LOCAL = np.column_stack((PLATFORM_POINTS_LOCAL_XY, np.zeros(6)))


# =========================
# SERVO ARM ROTATION AXES
# =========================
# Each servo arm rotates in a vertical plane, meaning its axis is horizontal.
# We define the axis direction vector (unit) for each servo shaft.
#
# The pair at indices 0/5 sits on the +x face with axes pointing +x; the other
# two pairs sit on the faces rotated +/-120 deg about Z.

def compute_servo_axes(shafts_xy: np.ndarray) -> np.ndarray:
    """Snap each shaft's outward radial direction to the nearest of the three
    face normals (0 deg, +120 deg, -120 deg about Z). The servo axis IS the
    outward face normal; arms rotate in the vertical plane perpendicular to it.
    """
    axes = []
    for (x, y) in shafts_xy:
        # Three face normals at 0, 120, -120 degrees
        candidates = [
            np.array([1.0, 0.0, 0.0]),
            np.array([np.cos(2*np.pi/3), np.sin(2*np.pi/3), 0.0]),
            np.array([np.cos(-2*np.pi/3), np.sin(-2*np.pi/3), 0.0]),
        ]

        # Choose closest by dot product with (x,y)
        radial = np.array([x, y, 0.0])
        radial /= np.linalg.norm(radial)

        best = max(candidates, key=lambda c: np.dot(c, radial))
        axes.append(best)

    return np.array(axes)


SERVO_AXES = compute_servo_axes(SERVO_SHAFTS_XY)


# =========================
# SERVO ROTATION DIRECTIONS
# =========================
# Adjacent servos are mirror-mounted, so command sense alternates by INDEX:
# indices 0, 2, 4 -> +1 (one sense), indices 1, 3, 5 -> -1 (opposite sense).

SERVO_SIGN = np.array([+1, -1, +1, -1, +1, -1], dtype=float)


# =========================
# DEFAULT SERVO NEUTRAL ANGLES
# =========================
SERVO_NEUTRAL_DEG = 90.0
